apiVersion: v1
kind: ReplicationController
metadata:
  name: example
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    name: example
  template:
    metadata:
      labels:
        name: example
    spec:
      containers:
      - name: example
        image: nginx
        ports:
        - containerPort: 28080
